---
- hosts: imageservers
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/root/.xbuild
        update=yes
        force=yes
    # node
    - command: /home/root/.xbuild/node-install v0.12.7 /home/root/.local/node
      args:
        creates: /home/root/.local/node/bin/node
    # python3
    - command: /home/root/.xbuild/python-install 3.4.3 /home/root/.local/python3
      args:
        creates: /home/root/.local/python3/bin/python
    # golang
    - command: /home/root/.xbuild/go-install 1.10 /home/root/.local/go
      args:
        creates: /home/root/.local/go/bin/go

- hosts: imageservers
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    # java
    - apt: name=openjdk-8-jdk state=present
