---
- hosts: imageservers
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/root/.xbuild
        update=yes
        force=yes
    # golang
    - command: /home/root/.xbuild/go-install 1.10 /home/root/.local/go
      args:
        creates: /home/root/.local/go/bin/go

- hosts: imageservers
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    # java
    - apt: name=openjdk-8-jdk state=present
