---
- hosts: imageservers
  gather_facts: no
  become: yes
  become_user: root
  tasks:
    - git:
        repo=https://github.com/isucon/isucon5-qualify.git
        dest=/tmp/isucon5-qualify
    - command: rsync -avz --delete /tmp/isucon5-qualify/webapp /home/isucon/
    # /home/isucon/webapp/{etc,go,java,nodejs,perl,php,python,ruby,scala,sql,static}
    - command: rm -rf /tmp/isucon5-qualify
      args:
        removes: /tmp/isucon5-qualify

    - name: go mod init
      shell: PATH=/home/isucon/.local/go/bin:$PATH GOROOT=/home/isucon/.local/go GOPATH=/home/isucon/webapp/go go mod init isucon5
      args:
        chdir: /home/isucon/webapp/go
    - name: go get mysql
      shell: PATH=/home/isucon/.local/go/bin:$PATH GOROOT=/home/isucon/.local/go GOPATH=/home/isucon/webapp/go go get github.com/go-sql-driver/mysql@latest
      args:
        chdir: /home/isucon/webapp/go
    - name: go get context
      shell: PATH=/home/isucon/.local/go/bin:$PATH GOROOT=/home/isucon/.local/go GOPATH=/home/isucon/webapp/go go get github.com/gorilla/context@latest
      args:
        chdir: /home/isucon/webapp/go
    - name: go get mux
      shell: PATH=/home/isucon/.local/go/bin:$PATH GOROOT=/home/isucon/.local/go GOPATH=/home/isucon/webapp/go go get github.com/gorilla/mux@latest
      args:
        chdir: /home/isucon/webapp/go
    - name: go get sessions
      shell: PATH=/home/isucon/.local/go/bin:$PATH GOROOT=/home/isucon/.local/go GOPATH=/home/isucon/webapp/go go get github.com/gorilla/sessions@latest
      args:
        chdir: /home/isucon/webapp/go
    - name: go build
      shell: PATH=/home/isucon/.local/go/bin:$PATH GOROOT=/home/isucon/.local/go GOPATH=/home/isucon/webapp/go go build -o app
      args:
        chdir: /home/isucon/webapp/go


  # post_tasks:
    # - command: sudo su - isucon /home/isucon/init.sh

- hosts: imageservers
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - copy: src=../files/env.sh dest=/home/isucon/env.sh owner=isucon mode=644
    - name: go (systemd)
      copy: src=../files/systemd.go.service dest=/etc/systemd/system/isuxi.go.service owner=root mode=644

    - name: default application selection
      service: name=isuxi.ruby state=running enabled=true
